- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present


- name: Install gnupg
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install rsync
  ansible.builtin.apt:
    name: rsync
    state: present

- name: Install vsftpd
  ansible.builtin.apt:
    name: vsftpd
    state: present